[project]

name = "adaptivesswt"
version = "0.3.1"
description = "A package to calculate an Adaptive Synchrosqueezing Transform"

license = "MIT"

authors = [
    {name="Edgardo Marchi", email="edgardo.marchi@gmail.com"}
]

readme = "README.md"

keywords = ["Synchrosqueezing", "Wavelet", "Transform", "DSP"
]

classifiers = [
    # TODO: update this list to match your application: https://pypi.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 1 - Planning",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]

requires-python = ">=3.10,<3.13"

dependencies = [
    "pywavelets",
    "numpy",
    "numba",
    "click",
    "scipy",
    "pyopencl",
]

[project.urls]
homepage = "https://github.com/edgardomarchi/adaptivesswt"
repository = "https://github.com/edgardomarchi/adaptivesswt"

[tool.poetry.group.plot]
optional = true

[tool.poetry.group.plot.dependencies]
matplotlib = "*"

[tool.poetry.group.pandas]
optional = true
[tool.poetry.group.pandas.dependencies]
pandas = "*"

[tool.poetry.group.SoundFile]
optional = true
[tool.poetry.group.SoundFile.dependencies]
SoundFile = "*"


[tool.poetry.group.dev.dependencies]

# Formatters
isort = "^5"   # A Python utility / library to sort imports
black = "*"

# Linters
mypy = "*"
pydocstyle = "*"
pylint = "^2"

# Testing
pytest = "^5"
pytest-cov = "*"
pytest-describe = "*"
pytest-expecter = "*"
pytest-random = "*"
freezegun = "*"        # a mocking library for datetime

# Documentation
sphinx = "*"
pygments = "*"
doc8 = "*"
recommonmark = "*"
m2r2 = "*"

# Tooling
pre-commit = "*"
pyinstaller = "*"
sniffer = "*"
pyinotify = "*"
bump2version = "*"
cookiecutter = "*"

[tool.poetry.scripts]
adaptivesswt = "adaptivesswt.cli:cli"

test_sst = { callable = "adaptivesswt.sswt:main", extras = ["plot"] }
test_asst = { callable = "adaptivesswt.adaptivesswt:main", extras = ["plot"] }
check_asst_perf = { callable = "scripts.check_sswt_performance:main", extras = ["plot"] }
test_asst_mse = { callable = "scripts.mse_for_synthetic_signals:main", extras = ["plot"] }


[tool.black]

target-version = ["py310"]
skip-string-normalization = true

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
